### ISSUE TITLE
TODO: Баги, исправления, улучшения

### ISSUE THREAD

**Issue by nicothin** [nicothin/NTH-start-project#3]
- [x] В листинг кода текстовых полей вынести самый частый вариант для копипасты
- [x] Перенести примесь фокуса формы в файл миксинов формы
- [x] Убрать модификаторы размера
- [x] Выпадающие элементы: решить проблему клика в выпадающем блоке (происходит закрытие блока)
- [x] Перетащить стилизацию таблиц в БЭМ-блок таблиц (как можно сильне отвязаться от глобальных стилей)
- [x] Перетащить стилизацию элементов форм в соответствующие БЭМ-блоки (как можно сильне отвязаться от глобальных стилей)
- [x] Разнести стилизацию блоков и модификаторов в разные стилевые файлы.

**Comment by nicothin** [comment]
- [ ] Предупреждение при попытке импортировать в диспетчере подключений несуществующие файлы

**Comment by nicothin** [comment]
- [ ] Перетащить стилизацию таблиц в БЭМ-блок таблиц (как можно сильне отвязаться от глобальных стилей)
- [ ] Перетащить стилизацию элементов форм в соответствующие БЭМ-блоки (как можно сильне отвязаться от глобальных стилей)

**Comment by vostok1961** [comment]
Если сообщение 
`<div class="alert  alert--danger">
  <button class="alert__close" aria-label="Close">×</button>
  <p>Какое-то сообщение</p>
</div>`
выводится где-то внутри формы, то при нажатии на
`<button class="alert__close" aria-label="Close">×</button>`
сабмитится вся форма.

**Comment by nicothin** [comment]
@vostok1961 
можно новые ишью заводить по подобным вопросам.
добавьте `type="button"` для кнопки и она перестанет отправлять форму.

п.с.: для вставки блочного кода нужны три такие кавычки (`) перед началом и перед концом )
